const express = require('express');
const router = express.Router();

router.post('/countries/search', (req, res) => {
  const countries = [
    {
      version: 1,
      id: 1,
      code: 'COUNTRY001',
      name: 'Country Name 1',
      alias1: 'Alias 1',
      alias2: 'Alias 2',
      alias3: null,
      extName: 'Extended Name',
      extView: true,
      daylightSavingTime: false,
      usRestriction: false,
      area: {
        version: 1,
        id: 1,
        sequence: 1,
        keyCode: 'AREA001',
        code: 'AREA001',
        isoCode: null,
        externalCode: null,
        label: 'Area Label',
        extView: true,
        externalLabel: null,
        itemStatus: 'Active',
        businessKey: 'Area Business Key',
        new: false,
      },
      businessKey: 'Country Business Key',
      new: false,
    },
  ];

  res.json(countries);
});

router.post('/cities/search', (req, res) => {
  const citiesArray = [
    'Amsterdam',
    'Barcelona',
    'Cairo',
    'Dakar',
    'Edimburgo',
    'Florencia',
    'Ginebra',
    'Helsinki',
    'Istanbul',
    'Jerusalen',
    'Kiev',
    'Londres',
    'Madrid',
    'Nueva York',
    'Oslo',
    'Paris',
    'Quito',
    'Roma',
    'Sidney',
    'Tokio',
    'Utrecht',
    'Viena',
    'Wellington',
    'Xian',
    'Yakarta',
    'Zurich',
  ];

  const citiesWithCodes = citiesArray.map((city) => ({
    name: city,
    code: city.slice(0, 3).toUpperCase(),
  }));
  res.json(citiesWithCodes);
});

router.get('/quick-search/search', (req, res) => {
  const criteria = req.query.criteria.toLowerCase();
  console.log('criteria', criteria);

  const dummyData = [
    { code: 'US', name: 'United States' },
    { code: 'CA', name: 'Canada' },
    { code: 'MX', name: 'Mexico' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'DE', name: 'Germany' },
    { code: 'FR', name: 'France' },
    { code: 'IT', name: 'Italy' },
    { code: 'ES', name: 'Spain' },
    { code: 'JP', name: 'Japan' },
    { code: 'CN', name: 'China' },
    { code: 'IN', name: 'India' },
    { code: 'BR', name: 'Brazil' },
    { code: 'AU', name: 'Australia' },
    { code: 'RU', name: 'Russia' },
    { code: 'AR', name: 'Argentina' },
    { code: 'CL', name: 'Chile' },
    { code: 'ZA', name: 'South Africa' },
    { code: 'NG', name: 'Nigeria' },
    { code: 'EG', name: 'Egypt' },
    { code: 'SA', name: 'Saudi Arabia' },
  ];

  const searchResults = dummyData.filter((obj) =>
    obj.name.toLocaleLowerCase().includes(criteria)
  );
  console.log('searchResults', searchResults);

  res.json(searchResults);
});

router.get('/domains/domain/BUREAU/items', (req, res) => {
  const dummyData = [
    {
      sequence: 1,
      keyCode: 'NEWS',
      code: '001',
      isoCode: null,
      externalCode: null,
      label: 'News',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Madrid',
    },
    {
      sequence: 2,
      keyCode: 'SPORTS',
      code: '002',
      isoCode: null,
      externalCode: null,
      label: 'Sports',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Washington',
    },

    {
      sequence: 4,
      keyCode: 'MOVIES',
      code: '004',
      isoCode: null,
      externalCode: null,
      label: 'Movies',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Geneva',
    },
  ];

  res.json(dummyData);
});

router.get('/domains/domain/EVENT_TYPE/items', (req, res) => {
  const dummyData = [
    {
      sequence: 1,
      keyCode: 'NEWS',
      code: '001',
      isoCode: null,
      externalCode: null,
      label: 'News',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'News',
    },
    {
      sequence: 2,
      keyCode: 'SPORTS',
      code: '002',
      isoCode: null,
      externalCode: null,
      label: 'Sports',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Sports',
    },
    {
      sequence: 3,
      keyCode: 'ENTERTAINMENT',
      code: '003',
      isoCode: null,
      externalCode: null,
      label: 'Entertainment',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Entertainment',
    },
    {
      sequence: 4,
      keyCode: 'MOVIES',
      code: '004',
      isoCode: null,
      externalCode: null,
      label: 'Movies',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Movies',
    },
  ];
  res.json(dummyData);
});

router.get('/domains/domain/USER_GROUP/items', (req, res) => {
  const dummyData = [
    {
      sequence: 1,
      keyCode: 'NEWS',
      code: '001',
      isoCode: null,
      externalCode: null,
      label: 'News',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'News',
    },
    {
      sequence: 2,
      keyCode: 'SPORTS',
      code: '002',
      isoCode: null,
      externalCode: null,
      label: 'Sports',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Sports',
    },
    {
      sequence: 3,
      keyCode: 'ENTERTAINMENT',
      code: '003',
      isoCode: null,
      externalCode: null,
      label: 'Entertainment',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Entertainment',
    },
    {
      sequence: 4,
      keyCode: 'MOVIES',
      code: '004',
      isoCode: null,
      externalCode: null,
      label: 'Movies',
      extView: true,
      externalLabel: null,
      itemStatus: 'Active',
      name: 'Movies',
    },
  ];
  res.json(dummyData);
});

router.get('/users/groups/user@example.com', (req, res) => {
  res.json(['EVC', 'FINANCE']);
});

router.post('/users/groups/user@example.com/update', (req, res) => {
  res.json(['EVC', 'FINANCE']);
});

router.post('/events/search', (req, res) => {
  const dummyEventData = [
    {
      no: 1,
      id: 101,
      isParent: false,
      periodBegin: '2024-04-25',
      periodEnd: '2024-04-27',
      description: 'Annual Conference',
      eventType: 'Conference',
      city: 'New York',
      contract: 'ABC123',
      salesDeal: 'SD-001',
      status: 'Confirmed',
      deadline: '2024-04-20',
      category: 'Business',
      subCategory: 'Finance',
      office: 'Headquarters',
      quoteId: 'Q-001',
      notes: true,
      isPMO: true,
      parent: false,
    },
    {
      no: 2,
      id: 102,
      isParent: false,
      periodBegin: '2024-05-15',
      periodEnd: '2024-05-18',
      description: 'Product Launch',
      eventType: 'Product Launch',
      city: 'San Francisco',
      contract: 'DEF456',
      salesDeal: 'SD-002',
      status: 'Confirmed',
      deadline: '2024-05-10',
      category: 'Marketing',
      subCategory: 'Product Promotion',
      office: 'West Coast',
      quoteId: 'Q-002',
      notes: true,
      isPMO: false,
      parent: false,
    },
    {
      no: 3,
      id: 103,
      isParent: false,
      periodBegin: '2024-06-10',
      periodEnd: '2024-06-12',
      description: 'Tech Summit',
      eventType: 'Conference',
      city: 'London',
      contract: 'GHI789',
      salesDeal: 'SD-003',
      status: 'Confirmed',
      deadline: '2024-06-05',
      category: 'Technology',
      subCategory: 'Information Technology',
      office: 'Europe',
      quoteId: 'Q-003',
      notes: true,
      isPMO: false,
      parent: false,
    },
    {
      no: 4,
      id: 104,
      isParent: false,
      periodBegin: '2024-07-20',
      periodEnd: '2024-07-22',
      description: 'Music Festival',
      eventType: 'Festival',
      city: 'Rio de Janeiro',
      contract: 'JKL012',
      salesDeal: 'SD-004',
      status: 'Confirmed',
      deadline: '2024-07-15',
      category: 'Entertainment',
      subCategory: 'Music',
      office: 'South America',
      quoteId: 'Q-004',
      notes: true,
      isPMO: true,
      parent: true,
    },
    {
      no: 5,
      id: 105,
      isParent: false,
      periodBegin: '2024-08-15',
      periodEnd: '2024-08-18',
      description: 'Fashion Week',
      eventType: 'Fashion Show',
      city: 'Milan',
      contract: 'MNO345',
      salesDeal: 'SD-005',
      status: 'Confirmed',
      deadline: '2024-08-10',
      category: 'Fashion',
      subCategory: 'Fashion Shows',
      office: 'Europe',
      quoteId: 'Q-005',
      notes: true,
      isPMO: true,
      parent: false,
    },
    {
      no: 6,
      id: 106,
      isParent: false,
      periodBegin: '2024-09-05',
      periodEnd: '2024-09-08',
      description: 'Film Festival',
      eventType: 'Film Festival',
      city: 'Cannes',
      contract: 'PQR678',
      salesDeal: 'SD-006',
      status: 'Confirmed',
      deadline: '2024-08-30',
      category: 'Entertainment',
      subCategory: 'Film',
      office: 'Europe',
      quoteId: 'Q-006',
      notes: true,
      isPMO: false,
      parent: false,
    },
    {
      no: 7,
      id: 107,
      isParent: false,
      periodBegin: '2024-10-20',
      periodEnd: '2024-10-22',
      description: 'Food Expo',
      eventType: 'Exhibition',
      city: 'Tokyo',
      contract: 'STU901',
      salesDeal: 'SD-007',
      status: 'Confirmed',
      deadline: '2024-10-15',
      category: 'Food',
      subCategory: 'Expo',
      office: 'Asia',
      quoteId: 'Q-007',
      notes: true,
      isPMO: false,
      parent: true,
    },
    {
      no: 8,
      id: 108,
      isParent: false,
      periodBegin: '2024-11-15',
      periodEnd: '2024-11-18',
      description: 'Tech Conference',
      eventType: 'Conference',
      city: 'San Francisco',
      contract: 'UVW234',
      salesDeal: 'SD-008',
      status: 'Confirmed',
      deadline: '2024-11-10',
      category: 'Technology',
      subCategory: 'Information Technology',
      office: 'North America',
      quoteId: 'Q-008',
      notes: true,
      isPMO: false,
      parent: false,
    },
    {
      no: 9,
      id: 109,
      isParent: false,
      periodBegin: '2024-12-10',
      periodEnd: '2024-12-13',
      description: 'Music Festival',
      eventType: 'Music Festival',
      city: 'Austin',
      contract: 'XYZ567',
      salesDeal: 'SD-009',
      status: 'Confirmed',
      deadline: '2024-12-05',
      category: 'Entertainment',
      subCategory: 'Music',
      office: 'North America',
      quoteId: 'Q-009',
      notes: true,
      isPMO: false,
      parent: false,
    },
    {
      no: 10,
      id: 110,
      isParent: false,
      periodBegin: '2025-01-20',
      periodEnd: '2025-01-23',
      description: 'Auto Show',
      eventType: 'Auto Show',
      city: 'Detroit',
      contract: 'ABC123',
      salesDeal: 'SD-010',
      status: 'Confirmed',
      deadline: '2025-01-15',
      category: 'Automotive',
      subCategory: 'Expo',
      office: 'North America',
      quoteId: 'Q-010',
      notes: true,
      isPMO: true,
      parent: true,
    },
    {
      no: 11,
      id: 111,
      isParent: false,
      periodBegin: '2025-02-15',
      periodEnd: '2025-02-18',
      description: 'Tech Summit',
      eventType: 'Conference',
      city: 'London',
      contract: 'JKL789',
      salesDeal: 'SD-011',
      status: 'Confirmed',
      deadline: '2025-02-10',
      category: 'Technology',
      subCategory: 'Information Technology',
      office: 'Europe',
      quoteId: 'Q-011',
      notes: true,
      isPMO: true,
      parent: true,
    },
    {
      no: 12,
      id: 112,
      isParent: true,
      periodBegin: '2025-03-20',
      periodEnd: '2025-03-23',
      description: 'Fashion Week',
      eventType: 'Fashion Show',
      city: 'New York',
      contract: 'MNO345',
      salesDeal: 'SD-012',
      status: 'Confirmed',
      deadline: '2025-03-15',
      category: 'Fashion',
      subCategory: 'Fashion Shows',
      office: 'North America',
      quoteId: 'Q-012',
      notes: true,
      isPMO: true,
      parent: true,
    },
  ];
  res.json(dummyEventData);
});

router.post('/organizations/result/search', (req, res) => {
  const organizations = [
    {
      id: 1,
      version: 1,
      code: 'ORG001',
      name: 'Organization 1',
      country: {
        id: 1,
        code: 'COUNTRY001',
        name: 'Country 1',
        alias1: 'Alias 1',
        alias2: 'Alias 2',
        alias3: 'Alias 3',
        extName: 'Extended Name',
        utc: '+01:00',
        extView: 'true',
        businessKey: 'Country Business Key',
        new: false,
      },
      financialStatusType: 'Financial Status Type 1',
      type: 'Organization Type 1',
      customer: 'Customer 1',
      provider: 'Provider 1',
      active: 'Active',
      defaultCity: {
        id: 1,
        code: 'CITY001',
        name: 'City 1',
        alias1: 'Alias 1',
        alias2: 'Alias 2',
        alias3: 'Alias 3',
        country: {
          id: 1,
          code: 'COUNTRY001',
          name: 'Country 1',
          alias1: 'Alias 1',
          alias2: 'Alias 2',
          alias3: 'Alias 3',
          extName: 'Extended Name',
          utc: '+01:00',
          extView: 'true',
          businessKey: 'Country Business Key',
          new: false,
        },
        extName: 'Extended Name',
        utc: '+01:00',
        extView: 'true',
        businessKey: 'City Business Key',
        new: false,
      },
      defaultPhone: 'Default Phone 1',
      poRefMandatory: 'PO Ref Mandatory 1',
      billedCurrencyLocked: 'Billed Currency Locked 1',
      defaultMail: 'Default Mail 1',
      defaultSystem: {
        id: 1,
        code: 'TYPE001',
        name: 'Type 1',
        extView: 'true',
        businessKey: 'Type Business Key 1',
        new: false,
      },
    },
    {
      id: 2,
      version: 1,
      code: 'ORG002',
      name: 'Organization 2',
      country: {
        id: 2,
        code: 'COUNTRY002',
        name: 'Country 2',
        alias1: 'Alias 1',
        alias2: 'Alias 2',
        alias3: 'Alias 3',
        extName: 'Extended Name',
        utc: '+02:00',
        extView: 'true',
        businessKey: 'Country Business Key',
        new: false,
      },
      financialStatusType: 'Financial Status Type 2',
      type: 'Organization Type 2',
      customer: 'Customer 2',
      provider: 'Provider 2',
      active: 'Active',
      defaultCity: {
        id: 2,
        code: 'CITY002',
        name: 'City 2',
        alias1: 'Alias 1',
        alias2: 'Alias 2',
        alias3: 'Alias 3',
        country: {
          id: 2,
          code: 'COUNTRY002',
          name: 'Country 2',
          alias1: 'Alias 1',
          alias2: 'Alias 2',
          alias3: 'Alias 3',
          extName: 'Extended Name',
          utc: '+02:00',
          extView: 'true',
          businessKey: 'Country Business Key',
          new: false,
        },
        extName: 'Extended Name',
        utc: '+02:00',
        extView: 'true',
        businessKey: 'City Business Key',
        new: false,
      },
      defaultPhone: 'Default Phone 2',
      poRefMandatory: 'PO Ref Mandatory 2',
      billedCurrencyLocked: 'Billed Currency Locked 2',
      defaultMail: 'Default Mail 2',
      defaultSystem: {
        id: 2,
        code: 'TYPE002',
        name: 'Type 2',
        extView: 'true',
        businessKey: 'Type Business Key 2',
        new: false,
      },
    },
    {
      id: 3,
      version: 1,
      code: 'ORG003',
      name: 'Organization 3',
      country: {
        id: 3,
        code: 'COUNTRY003',
        name: 'Country 3',
        alias1: 'Alias 1',
        alias2: 'Alias 2',
        alias3: 'Alias 3',
        extName: 'Extended Name',
        utc: '+03:00',
        extView: 'true',
        businessKey: 'Country Business Key',
        new: false,
      },
      financialStatusType: 'Financial Status Type 3',
      type: 'Organization Type 3',
      customer: 'Customer 3',
      provider: 'Provider 3',
      active: 'Active',
      defaultCity: {
        id: 3,
        code: 'CITY003',
        name: 'City 3',
        alias1: 'Alias 1',
        alias2: 'Alias 2',
        alias3: 'Alias 3',
        country: {
          id: 3,
          code: 'COUNTRY003',
          name: 'Country 3',
          alias1: 'Alias 1',
          alias2: 'Alias 2',
          alias3: 'Alias 3',
          extName: 'Extended Name',
          utc: '+03:00',
          extView: 'true',
          businessKey: 'Country Business Key',
          new: false,
        },
        extName: 'Extended Name',
        utc: '+03:00',
        extView: 'true',
        businessKey: 'City Business Key',
        new: false,
      },
      defaultPhone: 'Default Phone 3',
      poRefMandatory: 'PO Ref Mandatory 3',
      billedCurrencyLocked: 'Billed Currency Locked 3',
      defaultMail: 'Default Mail 3',
      defaultSystem: {
        id: 3,
        code: 'TYPE003',
        name: 'Type 3',
        extView: 'true',
        businessKey: 'Type Business Key 3',
        new: false,
      },
    },
    {
      id: 4,
      version: 1,
      code: 'ORG004',
      name: 'Organization 4',
      country: {
        id: 4,
        code: 'COUNTRY004',
        name: 'Country 4',
        alias1: 'Alias 1',
        alias2: 'Alias 2',
        alias3: 'Alias 3',
        extName: 'Extended Name',
        utc: '+04:00',
        extView: 'true',
        businessKey: 'Country Business Key',
        new: false,
      },
      financialStatusType: 'Financial Status Type 4',
      type: 'Organization Type 4',
      customer: 'Customer 4',
      provider: 'Provider 4',
      active: 'Active',
      defaultCity: {
        id: 4,
        code: 'CITY004',
        name: 'City 4',
        alias1: 'Alias 1',
        alias2: 'Alias 2',
        alias3: 'Alias 3',
        country: {
          id: 4,
          code: 'COUNTRY004',
          name: 'Country 4',
          alias1: 'Alias 1',
          alias2: 'Alias 2',
          alias3: 'Alias 3',
          extName: 'Extended Name',
          utc: '+04:00',
          extView: 'true',
          businessKey: 'Country Business Key',
          new: false,
        },
        extName: 'Extended Name',
        utc: '+04:00',
        extView: 'true',
        businessKey: 'City Business Key',
        new: false,
      },
      defaultPhone: 'Default Phone 4',
      poRefMandatory: 'PO Ref Mandatory 4',
      billedCurrencyLocked: 'Billed Currency Locked 4',
      defaultMail: 'Default Mail 4',
      defaultSystem: {
        id: 4,
        code: 'TYPE004',
        name: 'Type 4',
        extView: 'true',
        businessKey: 'Type Business Key 4',
        new: false,
      },
    },
  ];

  res.json(organizations);
});

router.get('/domains/list-all', (req, res) => {
  const domainListsResponse = {
    domainParameters: [
      {
        version: 1,
        id: 1,
        keyCode: 'KEY001',
        code: 'PARAM001',
        label: 'Parameter 1',
        groupCode: 'DOMAIN PARAMETER',
        externalLabel: null,
        domainStatus: 'Active',
        items: [
          {
            sequence: 1,
            keyCode: 'ABC',
            code: '001',
            isoCode: null,
            externalCode: null,
            label: 'Item 1',
            extView: true,
            externalLabel: null,
            itemStatus: 'Active',
            name: 'Dummy Item 1',
          },
        ],
        isModified: false,
        isRemoved: false,
        businessKey: 'Business Key 1',
        new: false,
      },
      {
        version: 1,
        id: 2,
        keyCode: 'KEY002',
        code: 'PARAM002',
        label: 'Parameter 2',
        groupCode: 'PROPERTY PARAMETER',
        externalLabel: null,
        domainStatus: 'Active',
        items: [
          {
            sequence: 1,
            keyCode: 'GHI',
            code: '003',
            isoCode: null,
            externalCode: null,
            label: 'Item 3',
            extView: true,
            externalLabel: null,
            itemStatus: 'Active',
            name: 'Dummy Item 3',
          },
        ],
        isModified: false,
        isRemoved: false,
        businessKey: 'Business Key 2',
        new: false,
      },
      {
        version: 1,
        id: 3,
        keyCode: 'KEY003',
        code: 'PARAM003',
        label: 'Parameter 3',
        groupCode: 'GROUP003',
        externalLabel: null,
        domainStatus: 'Active',
        items: [
          {
            sequence: 1,
            keyCode: 'JKL',
            code: '004',
            isoCode: null,
            externalCode: null,
            label: 'Item 4',
            extView: true,
            externalLabel: null,
            itemStatus: 'Active',
            name: 'Dummy Item 4',
          },
        ],
        isModified: false,
        isRemoved: false,
        businessKey: 'Business Key 3',
        new: false,
      },
    ],
    domainMappings: [
      {
        version: 1,
        id: 1,
        mappingType: 'Type 1',
        item: {
          sequence: 1,
          keyCode: 'ABC',
          code: '001',
          isoCode: null,
          externalCode: null,
          label: 'Item 1',
          extView: true,
          externalLabel: null,
          itemStatus: 'Active',
          name: 'Dummy Item 1',
        },
        mappedItems: [
          {
            version: 1,
            id: 1,
            item: {
              sequence: 1,
              keyCode: 'DEF',
              code: '002',
              isoCode: null,
              externalCode: null,
              label: 'Item 2',
              extView: true,
              externalLabel: null,
              itemStatus: 'Active',
              name: 'Dummy Item 2',
            },
            businessKey: 'Business Key 2',
            new: false,
          },
        ],
        isModified: false,
        isRemoved: false,
        businessKey: 'Business Key 3',
        new: false,
      },
      {
        version: 1,
        id: 2,
        mappingType: 'Type 2',
        item: {
          sequence: 1,
          keyCode: 'MNO',
          code: '005',
          isoCode: null,
          externalCode: null,
          label: 'Item 5',
          extView: true,
          externalLabel: null,
          itemStatus: 'Active',
          name: 'Dummy Item 5',
        },
        mappedItems: [
          {
            version: 1,
            id: 2,
            item: {
              sequence: 1,
              keyCode: 'PQR',
              code: '006',
              isoCode: null,
              externalCode: null,
              label: 'Item 6',
              extView: true,
              externalLabel: null,
              itemStatus: 'Active',
              name: 'Dummy Item 6',
            },
            businessKey: 'Business Key 4',
            new: false,
          },
        ],
        isModified: false,
        isRemoved: false,
        businessKey: 'Business Key 5',
        new: false,
      },
    ],
  };

  res.json(domainListsResponse);
});

router.post('/organizations/embedded/search', (req, res) => {
  const organizationData = [
    {
      code: 'ORG001',
      name: 'Company A',
      type: 'Public',
      isActive: true,
      isPoRefMandatory: false,
      financialStatusType: 'Stable',
      invoice: true,
    },
    {
      code: 'ORG002',
      name: 'Company B',
      type: 'Private',
      isActive: true,
      isPoRefMandatory: true,
      financialStatusType: 'Unstable',
      invoice: false,
    },
    {
      code: 'ORG003',
      name: 'Company C',
      type: 'Public',
      isActive: false,
      isPoRefMandatory: true,
      financialStatusType: 'Stable',
      invoice: true,
    },
    {
      code: 'ORG004',
      name: 'Company D',
      type: 'Private',
      isActive: true,
      isPoRefMandatory: false,
      financialStatusType: 'Stable',
      invoice: true,
    },
    {
      code: 'ORG005',
      name: 'Company E',
      type: 'Public',
      isActive: true,
      isPoRefMandatory: true,
      financialStatusType: 'Unstable',
      invoice: true,
    },
    {
      code: 'ORG006',
      name: 'Company F',
      type: 'Private',
      isActive: false,
      isPoRefMandatory: false,
      financialStatusType: 'Stable',
      invoice: false,
    },
    {
      code: 'ORG007',
      name: 'Company G',
      type: 'Public',
      isActive: true,
      isPoRefMandatory: true,
      financialStatusType: 'Stable',
      invoice: true,
    },
    {
      code: 'ORG008',
      name: 'Company H',
      type: 'Private',
      isActive: true,
      isPoRefMandatory: false,
      financialStatusType: 'Unstable',
      invoice: false,
    },
    {
      code: 'ORG009',
      name: 'Company I',
      type: 'Public',
      isActive: false,
      isPoRefMandatory: true,
      financialStatusType: 'Stable',
      invoice: true,
    },
    {
      code: 'ORG010',
      name: 'Company J',
      type: 'Private',
      isActive: true,
      isPoRefMandatory: true,
      financialStatusType: 'Stable',
      invoice: true,
    },
  ];
  res.json(organizationData);
});

router.post('/products/light/search', (req, res) => {
  res.json(
    (fakeProducts = [
      {
        id: 317,
        version: 1,
        code: 'CDN',
        name: 'Content Delivery Network',
        productType: 'OTHER',
        productCategory: 'NONTRANSMISSION',
        isMainProduct: true,
        isAssociatedProduct: false,
        price: {
          amount: 0.0,
          currency: {
            version: 0,
            id: 170,
            code: 'EUR',
            name: 'EUR',
            businessKey: 'EUR',
            new: false,
          },
          negative: false,
          zero: true,
          positive: false,
          notZero: false,
        },
        priceUnit: 'UNIT',
        invoiceOrganization: {
          id: 12791,
          version: 211,
          code: 'ZZEBU',
          name: 'European Broadcasting Union/Union Européenne de Radiotélévision',
        },
        deadline: null,
        quantity: 0,
        description:
          'Content delivery network such as Akamai used for live streaming and VOD. Product used to invoice customer according to Akamai invoices.',
        associatedProduct: false,
        mainProduct: true,
      },
    ])
  );
});

router.get('/loyalty-program', (req, res) => {
  const fakeLoyaltyPrograms = [
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 18.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'NO',
      isWithAssociatedProduct: 'NO',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'NEWS',
        name: 'News',
        type: 'AMEAC',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'INACTIVE',
        businessKey: 'SERVICE@SSDRA',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 19.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'ISPR',
        name: 'SPORTS',
        type: 'TMEMZ',
        isActive: true,
        isPoRefMandatory: true,
        financialStatusType: 'BL',
        invoice: true,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SFHG',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SFHG',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'YES',
      isWithAssociatedProduct: 'YES',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 15.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.6,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'NEWS',
        name: 'News',
        type: 'AMEAC',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'INACTIVE',
        businessKey: 'SERVICE@SSDRA',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'ISPR',
        name: 'SPORTS',
        type: 'TMEMZ',
        isActive: true,
        isPoRefMandatory: true,
        financialStatusType: 'BL',
        invoice: true,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SFHG',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SFHG',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'NO',
      isWithAssociatedProduct: 'NO',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 15.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'YES',
      isWithAssociatedProduct: 'YES',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 8.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'NEWS',
        name: 'News',
        type: 'AMEAC',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'INACTIVE',
        businessKey: 'SERVICE@SSDRA',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 2.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'ISPR',
        name: 'SPORTS',
        type: 'TMEMZ',
        isActive: true,
        isPoRefMandatory: true,
        financialStatusType: 'BL',
        invoice: true,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SFHG',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SFHG',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 0.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 15.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 24.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 27.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'NEWS',
        name: 'News',
        type: 'AMEAC',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'INACTIVE',
        businessKey: 'SERVICE@SSDRA',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'ISPR',
        name: 'SPORTS',
        type: 'TMEMZ',
        isActive: true,
        isPoRefMandatory: true,
        financialStatusType: 'BL',
        invoice: true,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SFHG',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SFHG',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'NEWS',
        name: 'News',
        type: 'AMEAC',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'INACTIVE',
        businessKey: 'SERVICE@SSDRA',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'ISPR',
        name: 'SPORTS',
        type: 'TMEMZ',
        isActive: true,
        isPoRefMandatory: true,
        financialStatusType: 'BL',
        invoice: true,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SFHG',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SFHG',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'NEWS',
        name: 'News',
        type: 'AMEAC',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'INACTIVE',
        businessKey: 'SERVICE@SSDRA',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'ISPR',
        name: 'SPORTS',
        type: 'TMEMZ',
        isActive: true,
        isPoRefMandatory: true,
        financialStatusType: 'BL',
        invoice: true,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SFHG',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SFHG',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
    {
      id: 5,
      version: 2,
      organization: {
        id: 7553,
        version: 374,
        code: 'IRPRES',
        name: 'Press TV',
        type: 'NMEMB',
        isActive: true,
        isPoRefMandatory: false,
        financialStatusType: 'BL',
        invoice: false,
      },
      service: {
        version: 0,
        id: 1688,
        sequence: 100,
        keyCode: 'SERVICE@SPEV',
        code: 'SPEV',
        isoCode: null,
        externalCode: null,
        label: 'Special Events',
        extView: true,
        externalLabel: null,
        itemStatus: 'ACTIVE',
        businessKey: 'SERVICE@SPEV',
        new: false,
      },
      product: null,
      startDate: [2016, 2, 1],
      endDate: [2017, 12, 31],
      startTime: null,
      endTime: null,
      discount: 20.0,
      accumulated: false,
      discountType: 'PERCENT',
      isModified: false,
      isRemoved: false,
      isOssOrigin: 'BOTH',
      isWithAssociatedProduct: 'BOTH',
    },
  ];
  res.json(fakeLoyaltyPrograms);
});

router.get('/roles', (req, res) => {
  const role = [
    {
      users: 'ROLE_STARGAZER_USERS',
      administrators: 'ROLE_STARGAZER_ADMINISTRATORS',
      resource_manager: 'ROLE_STARGAZER_RESOURCE_MANAGER',
      pricing_admin: 'ROLE_STARGAZER_PRICING_ADMIN',
      billing_admin: 'ROLE_STARGAZER_BILLING_ADMIN',
      viewer: 'ROLE_STARGAZER_VIEWER',
    },
  ];
  res.json(role);
});

router.get('/users/authentication', (req, res) => {
  const userPermissions = {
    permissions: ['PERM_DEFAULT_READ', 'PERM_DEFAULT_EDIT'],
    roles: ['ROLE_STARGAZER_ADMINISTRATORS'],
    userName: 'exampleUser',
    email: 'user@example.com',
    initials: 'EU',
    userPrincipalName: 'user@example.com',
  };
  res.json(userPermissions);
});

router.post('/incidents/owner/search', (req, res) => {
  res.json({
    id: 1,
    code: 'A',
    label: 'B',
  });
});

router.post('/incidents/category/search', (req, res) => {
  res.json({
    id: 1,
    code: 'A',
    label: 'B',
  });
});

router.post('/transmissions/search-criteria-light', (req, res) => {
  fakeTransmissions = [
    {
      id: 4104,
      version: 13,
      no: '00-1',
      title: 'UEL MD11 - Highlights',
      description: 'Start: 0900 GMT',
      startDate: [2016, 4, 8, 8, 45],
      endDate: [2016, 4, 8, 10, 0],
      status: 'COMPLETED',
      event: {
        id: 10388,
        version: 7,
        periodBegin: [2015, 8, 6],
        periodEnd: [2016, 6, 1],
        no: 35339,
        description: 'FOOTBALL: UEFA Distribution over Africa',
        eventType: {
          id: 3137,
          version: 220,
          sequence: 8,
          keyCode: 'EVENT_TYPE@PROG',
          code: 'PROG',
          externalCode: null,
          label: 'Programme',
          extView: true,
          externalLabel: null,
          itemStatus: 'ACTIVE',
        },
      },
    },
    {
      id: 368585,
      version: 2,
      no: '00-2',
      title: 'UCL MAGAZINE SHOW#9',
      description: 'MD4 PREVIEW',
      startDate: [1900, 1, 27, 11, 45],
      endDate: [1900, 1, 27, 13, 0],
      status: 'COMPLETED',
      event: {
        id: 14723,
        version: 3,
        periodBegin: [2017, 8, 1],
        periodEnd: [2018, 6, 4],
        no: 41525,
        description: 'FOOTBALL: UCL MAGAZINE PROGRAMS 2017-2018',
        eventType: {
          id: 3137,
          version: 220,
          sequence: 8,
          keyCode: 'EVENT_TYPE@PROG',
          code: 'PROG',
          externalCode: null,
          label: 'Programme',
          extView: true,
          externalLabel: null,
          itemStatus: 'ACTIVE',
        },
      },
    },
  ];
  res.json(fakeTransmissions);
});

router.post('/resources/search', (req, res) => {
  fakeResources = [
    {
      id: 1111487,
      version: 10,
      type: 'NETWORK',
      code: 'UEFA 2023-2024 AMERICAS EQUIP',
      codeLocal: 'UEFA 2023-2024 AMERICAS EQUIP',
      name: 'UEFA 2023-2024 AMERICAS EQUIP',
      externalName: null,
      blackListed: false,
    },
    {
      id: 1111715,
      version: 7,
      type: 'NETWORK',
      code: 'UEFA 2024 UCL DIGICON 1',
      codeLocal: 'UEFA 2024 UCL DIGICON 1',
      name: 'UEFA 2024 UCL DIGICON 1',
      externalName: null,
      blackListed: false,
    },
  ];
  res.json(fakeResources);
});

router.post('/resources/findResourceList', (req, res) => {
  res.json([
    {
      id: 1,
      code: '',
      version: 0,
      name: 'resource',
      codeLocal: 'Localresource',
      blackListed: false,
      type: 'type',
    },
  ]);
});

router.post('/organizations/findOrganizationList', (req, res) => {
  res.json([
    {
      id: 1,
      code: 'COD1',
      version: 0,
      name: 'resource',
      type: 'type',
      isActive: true,
      financialStatusType: 'active',
      invoice: true,
      isPoRefMandatory: false,
    },
  ]);
});

module.exports = router;
